<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <RootNamespace>VTBL.Restrict.Loader.Infrastructure</RootNamespace>
    <AssemblyName>VTBL.Restrict.Loader.Infrastructure</AssemblyName>
    <Nullable>disable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="5.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="5.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="5.0.0" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="5.0.0" />
    <PackageReference Include="RabbitMQ.Client" Version="6.2.4" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\VTBL.Restrict.Loader.Application\VTBL.Restrict.Loader.Application.csproj" />
    <ProjectReference Include="..\VTBL.Restrict.Loader.Context\VTBL.Restrict.Loader.Context.csproj" />
    <ProjectReference Include="..\VTBL.Restrict.Loader.Domain\VTBL.Restrict.Loader.Domain.csproj" />
  </ItemGroup>
</Project>
